default:
  tier: prod
  project_id: "nih-nci-dceg-connect-prod-6d04"
  project_number: "155089172944"
  write_to_gcs: TRUE
  bucket: gs://ccc_weekly_metrics_report
  box_app: NCI_BOX_GCP_CONNECT4CANCER_PROD
  box_folder: "211674408263"
  flag: ""
biospecimen:
  QC_REPORT: biospecimen
  rules_file: qc_rules_biospecimen.xlsx
  flag: "export2box"
  box_folder: "221297686961"
recruitment:
  QC_REPORT: recruitment
  rules_file: qc_rules_recruitment.xlsx
module1:
  QC_REPORT: module1
  rules_file: qc_rules_module1.xlsx
  flag: "export2box"
  box_folder: "203464977998"
module2:
  QC_REPORT: module2
  rules_file: qc_rules_module2.xlsx
  flag: "export2box"
module3:
  QC_REPORT: module3
  rules_file: qc_rules_module3.xlsx
  flag: "export2box"
module4:
  QC_REPORT: module4
  rules_file: qc_rules_module4.xlsx
  flag: "export2box"
